name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      PYTEST_ADDOPTS: -ra -vv

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify repo root & requirements
        run: |
          pwd
          ls -la
          echo "---- requirements.txt ----"
          cat requirements.txt

      - name: Upgrade pip & install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip show pytest || (echo "pytest not installed" && exit 1)
          python -m pip freeze | sed -n '1,120p'

      - name: Run tests
        run: |
          python -c "import sys,os;print('PYTHONPATH=',os.environ.get('PYTHONPATH'));print('sys.executable=',sys.executable)"
          python -m pytest
